<a href="https://colab.research.google.com/github/bjungweapon/mjc.ai.ml/blob/BDU/bdu.9.1.logistic.iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import sklearn

# 로지스틱 회귀 분류 모델을 위한 패키지 임포트
from sklearn.linear_model import LogisticRegression

# 학습 및 뎉트 데이터셋 분리를 위한 패키지 임포트
from sklearn.model_selection import train_test_split

In [ ]:
# call data
df = pd.read_csv ("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv")

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

df[["sepal_length"]] = scaler.fit_transform(df[["sepal_length"]])
df[["sepal_width"]] = scaler.fit_transform(df[["sepal_width"]])
df[["petal_length"]] = scaler.fit_transform(df[["petal_length"]])
df[["petal_width"]] = scaler.fit_transform(df[["petal_width"]])

In [ ]:
df


sepal_length  sepal_width  petal_length  petal_width    species
0        0.222222     0.625000      0.067797     0.041667     setosa
1        0.166667     0.416667      0.067797     0.041667     setosa
2        0.111111     0.500000      0.050847     0.041667     setosa
3        0.083333     0.458333      0.084746     0.041667     setosa
4        0.194444     0.666667      0.067797     0.041667     setosa
..            ...          ...           ...          ...        ...
145      0.666667     0.416667      0.711864     0.916667  virginica
146      0.555556     0.208333      0.677966     0.750000  virginica
147      0.611111     0.416667      0.711864     0.791667  virginica
148      0.527778     0.583333      0.745763     0.916667  virginica
149      0.444444     0.416667      0.694915     0.708333  virginica

[150 rows x 5 columns]

In [ ]:
X=df[["sepal_length","sepal_width","petal_length","petal_width"]]
y=df[["species"]]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=11)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(120, 4)
(30, 4)
(120, 1)
(30, 1)


In [ ]:
## DATA 분석 실행

In [ ]:
#logisticRegression 객체 생성
lr = LogisticRegression()
lr.fit(X_train, y_train)

C:\Users\cst_3\anaconda3\envs\vconda_jungbg\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [ ]:
pred = lr.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score
acc = accuracy_score(y_test, pred)
print(acc)

0.8333333333333334


In [ ]:
## 모델 선능 평가.  CONFUSION MATRIX

In [ ]:
from sklearn.metrics import confusion_matrix
mat = confusion_matrix(y_test, pred)
print(mat)

[[9 0 0]
 [0 7 3]
 [0 2 9]]


In [ ]:
## 모델 성능 평가 - 평가 지표 계산

In [ ]:
from sklearn.metrics import classification_report
rpt = classification_report(y_test, pred)
print(rpt)

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00         9
  versicolor       0.78      0.70      0.74        10
   virginica       0.75      0.82      0.78        11

    accuracy                           0.83        30
   macro avg       0.84      0.84      0.84        30
weighted avg       0.83      0.83      0.83        30



In [ ]:
## 위 결과를 보면... setosa f1-score 값이 좋음 (value 1 )
## versicolor, virginica 에 대해서는 0.7, 0.8 정도로 약간 떨어진다.
## setosa는 매우 신뢰 있다.
## accurary는 0.83

## KNN 알고 리즘으로 동일하게 분석 해 봤다.
## 분석을 수생하는 것만 다르다.
## 성능 평가도 동일하다.
## 오히려 KNN이 0.93 으로 더 높다.
## 여러개의 알고리즘을 사용할 수 있다.  ( 왜 차이가 나는가?  모아진 data에 따라서 차이가 있다.)