<a href="https://colab.research.google.com/github/bjungweapon/mjc.ai.ml/blob/BDU/bud.7.1.2.basic_da.iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 분석 model 을 사용한다.

1. 필요 pkg import
2. 분류 model 어떤것 사용할지를 선택하고 import 한다.
3. model selection을 위해서 sklearn의 train_test_split를 import 한다.

# 1. 데이터 전처리
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# 2. 훈련/테스트 데이터 분할
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.3)

# 3. 모델 학습
model.fit(X_train, y_train)

# 4. 예측
y_pred = model.predict(X_test)

# 5. 평가
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))


In [78]:
import numpy as np
import pandas as pd
import sklearn

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [79]:
from sklearn.model_selection import train_test_split

In [80]:
print(sklearn.__version__)

1.6.1


1.2 data 불러오기

In [81]:
df = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv")

In [82]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

1.3 데이터 탐색

In [83]:
df.shape

(150, 5)

In [84]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [85]:
df.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

1.4 데이터 전처리

  붓꽃 종류를 숫자로 변경하자. (데이터 인코딩, 레이블 인코딩)


 setosa :0 vericolor: 1, versinica:2,


 include = True / False  (기존값 덮어쓰기 : True)


 object type (string)을  integer type으로 바꿀 때. replace () 사용의 예 참고.

In [86]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [87]:
df["species"].replace({"setosa":0, "versicolor":1, "virginica":2}, inplace=True)

<ipython-input-87-3e0b44c6f0f4>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["species"].replace({"setosa":0, "versicolor":1, "virginica":2}, inplace=True)
<ipython-input-87-3e0b44c6f0f4>:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["species"].replace({"setosa":0, "versicolor":1, "virgi

In [88]:
df

sepal_length  sepal_width  petal_length  petal_width  species
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

[150 rows x 5 columns]

1.5 분석 데이터 셋 준비

  독립 변수가 무엇인가? 와
  종속 변수가 무엇인가?  를  명확히 정의

  독립 변수는 꽃받침의  넓이와 길이, 꽃잎의 넓이와 길이
  종속 변수는 꽃 종류
  

In [89]:
X = df[ ["sepal_length","sepal_width","petal_length","petal_width"]]
y = df["species"]

In [90]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=11)

(*) random_state는 동일한 값을 seed로 해서 random 값이 출력되도록 하는 것.

In [91]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(120, 4)
(30, 4)
(120,)
(30,)


1.6 데이터 분석 수행
  결국은 주어진 데이터로 꽂 종류를 구분하는 문제.
  이 예제는 분류 문제
  

In [92]:
dt = DecisionTreeClassifier(random_state=11)   ## 알고리즘 종류.
dt.fit(X_train, y_train)   ## 중요 :: 학습 수행

DecisionTreeClassifier(random_state=11)

In [93]:
pred = dt.predict(X_test)   #예측.

print(y_test.values)   ##실제값과 한번 눈으로 비교해 보자. ( 실제 값)
print(pred) ##  (예측 값)

[2 2 2 1 2 0 1 0 0 1 2 1 1 2 2 0 2 1 2 2 1 0 0 1 0 0 2 1 0 1]
[2 2 1 1 2 0 1 0 0 1 1 1 1 2 2 0 2 1 2 2 1 0 0 1 0 0 2 1 0 1]


1.7 성능 평가 및 시각화

In [94]:
#모델 서능 - 정확도.

In [95]:
from sklearn.metrics import accuracy_score    ## 성능 평가를 위해서 accuracy_score 함수를 사용하자.

In [96]:
acc = accuracy_score(y_test, pred)
print(acc)

0.9333333333333333


In [97]:
from sklearn.metrics import confusion_matrix

In [98]:
confusion_matrix(y_test, pred)

array([[ 9,  0,  0],
       [ 0, 10,  0],
       [ 0,  2,  9]])

In [99]:
## 0 을 0 으로 분류한 것은 9, 2를 2로 분류한 것은 9개, 1을 1로 분류한 것은 10ro fh dkf tn dlTEk.

In [100]:
from sklearn.metrics import classification_report
rpt = classification_report(y_test, pred)
print(rpt)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       0.83      1.00      0.91        10
           2       1.00      0.82      0.90        11

    accuracy                           0.93        30
   macro avg       0.94      0.94      0.94        30
weighted avg       0.94      0.93      0.93        30



In [101]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, pred)

0.9333333333333333

In [105]:
## 오차 행렬 (Confustion matrix 를 사용해 보자)

from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, pred)

array([[ 9,  0,  0],
       [ 0, 10,  0],
       [ 0,  2,  9]])

from sklearn.metrics import precision_score
presicsion_score(y_test, pred, average=None)

In [102]:
from sklearn.metrics import precision_score

precision_score(y_test, y_pred, average=None)
precision_score(y_test,)

NameError: name 'y_pred' is not defined